apiVersion: v1
kind: Service
metadata:
  name: dummy15
  labels:
    app: dummy15
spec:
  selector:
    app: dummy15
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy15
  labels:
    app: dummy15
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy15
  template:
    metadata:
      labels:
        app: dummy15
    spec:
      containers:
        - name: dummy15
          image: docker.io/abrevnov/dummy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: CHILD_SERVICE
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: dummy7
  labels:
    app: dummy7
spec:
  selector:
    app: dummy7
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy7
  labels:
    app: dummy7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy7
  template:
    metadata:
      labels:
        app: dummy7
    spec:
      containers:
        - name: dummy7
          image: docker.io/abrevnov/dummy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: CHILD_SERVICE
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: dummy19
  labels:
    app: dummy19
spec:
  selector:
    app: dummy19
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy19
  labels:
    app: dummy19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy19
  template:
    metadata:
      labels:
        app: dummy19
    spec:
      containers:
        - name: dummy19
          image: docker.io/abrevnov/dummy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: CHILD_SERVICE
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: dummy16
  labels:
    app: dummy16
spec:
  selector:
    app: dummy16
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy16
  labels:
    app: dummy16
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy16
  template:
    metadata:
      labels:
        app: dummy16
    spec:
      containers:
        - name: dummy16
          image: docker.io/abrevnov/dummy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: CHILD_SERVICE
              value: "dummy17"
---
apiVersion: v1
kind: Service
metadata:
  name: dummy9
  labels:
    app: dummy9
spec:
  selector:
    app: dummy9
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy9
  labels:
    app: dummy9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy9
  template:
    metadata:
      labels:
        app: dummy9
    spec:
      containers:
        - name: dummy9
          image: docker.io/abrevnov/dummy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: CHILD_SERVICE
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: dummy1
  labels:
    app: dummy1
spec:
  selector:
    app: dummy1
  ports:
    - port: 8888
      targetPort: 8888
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy1
  labels:
    app: dummy1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy1
  template:
    metadata:
      labels:
        app: dummy1
    spec:
      containers:
        - name: dummy1
          image: docker.io/abrevnov/dummy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: CHILD_SERVICE
              value: "dummy2,dummy3"
---
apiVersion: v1
kind: Service
metadata:
  name: dummy17
  labels:
    app: dummy17
spec:
  selector:
    app: dummy17
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy17
  labels:
    app: dummy17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy17
  template:
    metadata:
      labels:
        app: dummy17
    spec:
      containers:
        - name: dummy17
          image: docker.io/abrevnov/dummy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: CHILD_SERVICE
              value: "dummy18,dummy19,dummy20"
---
apiVersion: v1
kind: Service
metadata:
  name: dummy20
  labels:
    app: dummy20
spec:
  selector:
    app: dummy20
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy20
  labels:
    app: dummy20
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy20
  template:
    metadata:
      labels:
        app: dummy20
    spec:
      containers:
        - name: dummy20
          image: docker.io/abrevnov/dummy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: CHILD_SERVICE
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: dummy3
  labels:
    app: dummy3
spec:
  selector:
    app: dummy3
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy3
  labels:
    app: dummy3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy3
  template:
    metadata:
      labels:
        app: dummy3
    spec:
      containers:
        - name: dummy3
          image: docker.io/abrevnov/dummy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: CHILD_SERVICE
              value: "dummy4,dummy5"
---
apiVersion: v1
kind: Service
metadata:
  name: dummy14
  labels:
    app: dummy14
spec:
  selector:
    app: dummy14
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy14
  labels:
    app: dummy14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy14
  template:
    metadata:
      labels:
        app: dummy14
    spec:
      containers:
        - name: dummy14
          image: docker.io/abrevnov/dummy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: CHILD_SERVICE
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: dummy10
  labels:
    app: dummy10
spec:
  selector:
    app: dummy10
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy10
  labels:
    app: dummy10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy10
  template:
    metadata:
      labels:
        app: dummy10
    spec:
      containers:
        - name: dummy10
          image: docker.io/abrevnov/dummy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: CHILD_SERVICE
              value: "dummy16"
---
apiVersion: v1
kind: Service
metadata:
  name: dummy6
  labels:
    app: dummy6
spec:
  selector:
    app: dummy6
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy6
  labels:
    app: dummy6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy6
  template:
    metadata:
      labels:
        app: dummy6
    spec:
      containers:
        - name: dummy6
          image: docker.io/abrevnov/dummy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: CHILD_SERVICE
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: dummy11
  labels:
    app: dummy11
spec:
  selector:
    app: dummy11
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy11
  labels:
    app: dummy11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy11
  template:
    metadata:
      labels:
        app: dummy11
    spec:
      containers:
        - name: dummy11
          image: docker.io/abrevnov/dummy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: CHILD_SERVICE
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: dummy4
  labels:
    app: dummy4
spec:
  selector:
    app: dummy4
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy4
  labels:
    app: dummy4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy4
  template:
    metadata:
      labels:
        app: dummy4
    spec:
      containers:
        - name: dummy4
          image: docker.io/abrevnov/dummy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: CHILD_SERVICE
              value: "dummy6,dummy7,dummy8"
---
apiVersion: v1
kind: Service
metadata:
  name: dummy13
  labels:
    app: dummy13
spec:
  selector:
    app: dummy13
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy13
  labels:
    app: dummy13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy13
  template:
    metadata:
      labels:
        app: dummy13
    spec:
      containers:
        - name: dummy13
          image: docker.io/abrevnov/dummy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: CHILD_SERVICE
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: dummy2
  labels:
    app: dummy2
spec:
  selector:
    app: dummy2
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy2
  labels:
    app: dummy2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy2
  template:
    metadata:
      labels:
        app: dummy2
    spec:
      containers:
        - name: dummy2
          image: docker.io/abrevnov/dummy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: CHILD_SERVICE
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: dummy18
  labels:
    app: dummy18
spec:
  selector:
    app: dummy18
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy18
  labels:
    app: dummy18
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy18
  template:
    metadata:
      labels:
        app: dummy18
    spec:
      containers:
        - name: dummy18
          image: docker.io/abrevnov/dummy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: CHILD_SERVICE
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: dummy8
  labels:
    app: dummy8
spec:
  selector:
    app: dummy8
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy8
  labels:
    app: dummy8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy8
  template:
    metadata:
      labels:
        app: dummy8
    spec:
      containers:
        - name: dummy8
          image: docker.io/abrevnov/dummy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: CHILD_SERVICE
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: dummy5
  labels:
    app: dummy5
spec:
  selector:
    app: dummy5
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy5
  labels:
    app: dummy5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy5
  template:
    metadata:
      labels:
        app: dummy5
    spec:
      containers:
        - name: dummy5
          image: docker.io/abrevnov/dummy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: CHILD_SERVICE
              value: "dummy9,dummy10,dummy11,dummy12,dummy13,dummy14,dummy15"
---
apiVersion: v1
kind: Service
metadata:
  name: dummy12
  labels:
    app: dummy12
spec:
  selector:
    app: dummy12
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy12
  labels:
    app: dummy12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy12
  template:
    metadata:
      labels:
        app: dummy12
    spec:
      containers:
        - name: dummy12
          image: docker.io/abrevnov/dummy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: CHILD_SERVICE
              value: ""